740
Infoland/iProva-REST-API-examples pull request #37
Opened 2024-05-14 06:34 UTC by sjoerdvanloon

2024-05-14 06:34 UTC, sjoerdvanloon commented
Prepped for 740

2024-09-16 07:26 UTC, LtDrak requested changes
Please check comments

2024-09-16 07:26 UTC, LtDrak commented on Changelog.md
> +Beta routes in 740 these routes are still subject to change.
Beta routes; these are still subject to change

2024-09-16 07:26 UTC, LtDrak commented on Changelog.md
> +Added | **ANY** support/example_questions | // Added api for AI questions  functionality
// moet weg

2024-09-16 07:26 UTC, LtDrak commented on Changelog.md
> +Changed | **ANY** risks/control_templates | Added support for actions on control tests and control test reviews on the controle templates
control templates

2024-09-16 07:26 UTC, LtDrak commented on Changelog.md
> +Changed | **POST** risks | Property 'is_main_risk'
'added'

2024-09-16 07:26 UTC, LtDrak commented on Changelog.md
> +Added | **GET** documents/{document_id}/contents/{language} | Get the contents of a document in a certain language
Double check what this does

2024-09-16 07:30 UTC, sjoerdvanloon commented on Changelog.md
> +Added | **ANY** support/example_questions | // Added api for AI questions  functionality
Fixes

2024-09-16 07:38 UTC, LtDrak approved these changes

2024-09-16 07:38 UTC, merged